# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160824161817 on 2016-08-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160824_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(db_column='Address_id', primary_key=True, serialize=False)),
                ('district', models.CharField(db_column='District', max_length=50)),
                ('vdc_municipality', models.CharField(db_column='VDC_Municipality', max_length=50)),
                ('wardno', models.CharField(db_column='WardNo', max_length=5)),
            ],
            options={
                'db_table': 'Address',
                'managed': False,
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('citizenship_id', models.CharField(db_column='Citizenship_id', max_length=20, primary_key=True, serialize=False)),
                ('citizenshiptype', models.CharField(db_column='CitizenshipType', max_length=20)),
                ('birthdistrict', models.CharField(db_column='BirthDistrict', max_length=20)),
                ('issuedate', models.DateField(db_column='IssueDate')),
                ('dob', models.DateField(db_column='DOB')),
            ],
            options={
                'db_table': 'Citizenship',
                'managed': False,
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('disability_id', models.CharField(db_column='Disability_id', max_length=5, primary_key=True, serialize=False)),
                ('disabilitydescription', models.CharField(db_column='DisabilityDescription', max_length=50)),
            ],
            options={
                'db_table': 'Disability',
                'managed': False,
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='VoterInfo',
            fields=[
                ('voter_id', models.IntegerField(db_column='Voter_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('gender', models.CharField(db_column='Gender', max_length=1)),
                ('spousename', models.CharField(blank=True, db_column='SpouseName', max_length=50, null=True)),
                ('fathername', models.CharField(db_column='FatherName', max_length=50)),
                ('grandfathername', models.CharField(db_column='GrandFatherName', max_length=50)),
                ('mothertongue', models.CharField(db_column='MotherTongue', max_length=50)),
                ('mobile', models.CharField(db_column='Mobile', max_length=20)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('literacystatus', models.CharField(db_column='LiteracyStatus', max_length=1)),
                ('qualification', models.CharField(blank=True, db_column='Qualification', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Voter_info',
                'managed': False,
                'indexes': [],
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
